select
    `ProjectNo-10` as `project_no`,
    `Element-20` as `element`,
    `Description-21` as `description`,
    `Quantity-22` as `quantity`,
    `UnitofMeasure-23` as `unitof_measure`,
    `Description2-24` as `description_2`,
    `Chapter-31` as `chapter`,
    `Paragraph-32` as `paragraph`,
    `Level-40` as `level`,
    `StandardObject-45` as `standard_object`,
    `StartingDate-330` as `starting_date`,
    `StartingTime-335` as `starting_time`,
    `EndingDate-340` as `ending_date`,
    `EndingTime-345` as `ending_time`,
    `EstimatedHours-350` as `estimated_hours`,
    `FixedEstimation-355` as `fixed_estimation`,
    `Blocked-400` as `blocked`,
    `SearchCode-410` as `search_code`,
    `ElementType-420` as `element_type`,
    `PlanningActivityType-430` as `planning_activity_type`,
    `PreviousElement-470` as `previous_element`,
    `LeadTimeDays-480` as `lead_time_days`,
    `ResponsibleEmployee-490` as `responsible_employee`,
    `PublishinEmpolyApp-520` as `publishin_empoly_app`,
    `Discipline-530` as `discipline`,
    `PhaseCode-560` as `phase_code`,
    `BlockOutsideDateRange-580` as `block_outside_date_range`,
    `PlotBuildStage-600` as `plot_build_stage`,
    `INSBOUPurchaseOrderdefault-610` as `insbou_purchase_orderdefault`,
    `PlanningStatusCode-620` as `planning_status_code`,
    `ApproverHours-640` as `approver_hours`,
    `ApproverInvoice-650` as `approver_invoice`,
    `ApproverInvoiceApproval-660` as `approver_invoice_approval`,
    `ApproverAdviceOrder-670` as `approver_advice_order`,
    `ApproverPurchaseOrder-680` as `approver_purchase_order`,
    `ApproverPurchaseQuote-690` as `approver_purchase_quote`,
    `ApproverCreditMemo-700` as `approver_credit_memo`,
    `ApproverCreditMemoApproval-710` as `approver_credit_memo_approval`,
    `ApproverPurchaseRequisition-720` as `approver_purchase_requisition`,
    `ApproverNotPostedInvoice-730` as `approver_not_posted_invoice`,
    `ApproverNotPostedCrMemo-740` as `approver_not_posted_cr_memo`,
    `VisibleinGRP-11124900` as `visiblein_grp`,
    `timestamp-0` as `timestamp`,
    `systemId-2000000000` as `system_id`,
    `SystemCreatedAt-2000000001` as `system_created_at`,
    `SystemCreatedBy-2000000002` as `system_created_by`,
    `SystemModifiedAt-2000000003` as `system_modified_at`,
    `SystemModifiedBy-2000000004` as `system_modified_by`,
    `$Company` as `company`,
    _metadata
from
    stream read_files(
        '/Volumes/{{ var("source")["database"] }}/{{ var("source")["schema"] }}/{{ var("source")["volume"] }}/deltas/ProjectElement-11012010/*.csv',
        schema
        => '`ProjectNo-10` string, `Element-20` string, `Description-21` string, `Quantity-22` decimal(12,5), `UnitofMeasure-23` string, `Description2-24` string, `Chapter-31` string, `Paragraph-32` string, `Level-40` int, `StandardObject-45` string, `StartingDate-330` date, `StartingTime-335` string, `EndingDate-340` date, `EndingTime-345` string, `EstimatedHours-350` decimal(12,5), `FixedEstimation-355` boolean, `Blocked-400` boolean, `SearchCode-410` string, `ElementType-420` string, `PlanningActivityType-430` string, `PreviousElement-470` string, `LeadTimeDays-480` decimal(12,5), `ResponsibleEmployee-490` string, `PublishinEmpolyApp-520` boolean, `Discipline-530` string, `PhaseCode-560` string, `BlockOutsideDateRange-580` boolean, `PlotBuildStage-600` boolean, `INSBOUPurchaseOrderdefault-610` boolean, `PlanningStatusCode-620` string, `ApproverHours-640` string, `ApproverInvoice-650` string, `ApproverInvoiceApproval-660` string, `ApproverAdviceOrder-670` string, `ApproverPurchaseOrder-680` string, `ApproverPurchaseQuote-690` string, `ApproverCreditMemo-700` string, `ApproverCreditMemoApproval-710` string, `ApproverPurchaseRequisition-720` string, `ApproverNotPostedInvoice-730` string, `ApproverNotPostedCrMemo-740` string, `VisibleinGRP-11124900` boolean, `timestamp-0` bigint, `systemId-2000000000` string, `SystemCreatedAt-2000000001` timestamp, `SystemCreatedBy-2000000002` string, `SystemModifiedAt-2000000003` timestamp, `SystemModifiedBy-2000000004` string, `$Company` string',
        header => 'true',
        sep => ',',
        escape => '\\',
        encoding => 'UTF-8',
        quote => '"'
    )
