select
    `ProjectNo-10` as `project_no`,
    `Principal-20` as `principal`,
    `Scheme-25` as `scheme`,
    `InstallmentNo-30` as `installment_no`,
    `Description-40` as `description`,
    `CommissionNo-50` as `commission_no`,
    `CostObject-60` as `cost_object`,
    `VATProdPostingGroup-70` as `vat_prod_posting_group`,
    `InstallmentAmountLCY-80` as `installment_amount_lcy`,
    `InstallmentAmount-81` as `installment_amount`,
    `CurrencyCode-82` as `currency_code`,
    `InstallmentAmountInclVAT-83` as `installment_amount_incl_vat`,
    `Chargeable-90` as `chargeable`,
    `InvoicePriceLCY-100` as `invoice_price_lcy`,
    `InvoicePrice-101` as `invoice_price`,
    `ExtensionContract-140` as `extension_contract`,
    `PlotNo-150` as `plot_no`,
    `Option-160` as `option`,
    `MainGroup-165` as `main_group`,
    `Group-170` as `group`,
    `SubGroup-180` as `sub_group`,
    `Points-200` as `points`,
    `Pointstobeinvoiced-210` as `pointstobeinvoiced`,
    `Element-220` as `element`,
    `InstallmentMotivationDate-230` as `installment_motivation_date`,
    `InstallmentOverview-235` as `installment_overview`,
    `PercentagePoints-240` as `percentage_points`,
    `TotalPercentagePoints-245` as `total_percentage_points`,
    `ExpectedInvoiceDate-250` as `expected_invoice_date`,
    `LastInstallment-260` as `last_installment`,
    `DueDateBase-270` as `due_date_base`,
    `DueDateActual-290` as `due_date_actual`,
    `InterestInstallment-300` as `interest_installment`,
    `InterestInstNoContract-310` as `interest_inst_no_contract`,
    `InterestInstNoTransfer-320` as `interest_inst_no_transfer`,
    `InstallmentSchemeSerNo-330` as `installment_scheme_ser_no`,
    `PercentageContractAmount-340` as `percentage_contract_amount`,
    `CostComponent-360` as `cost_component`,
    `PeriodStart-410` as `period_start`,
    `PeriodEnd-420` as `period_end`,
    `VATAmountLongLease-430` as `vat_amount_long_lease`,
    `InvoiceVATAmountLongLease-440` as `invoice_vat_amount_long_lease`,
    `SpecificPaymentTermsCode-450` as `specific_payment_terms_code`,
    `ProjectActivityNo-500` as `project_activity_no`,
    `RAWFinalInstallment-510` as `raw_final_installment`,
    `OrigContractInstallmentDate-520` as `orig_contract_installment_date`,
    `Remarks-530` as `remarks`,
    `AdvancePayment-540` as `advance_payment`,
    `OptionQuoteNo-610` as `option_quote_no`,
    `SettlementSheetNo-620` as `settlement_sheet_no`,
    `InvoicePriceInclVATLCY-630` as `invoice_price_incl_vatlcy`,
    `InvoicePriceInclVAT-640` as `invoice_price_incl_vat`,
    `InstallAmntInclVATLCY-650` as `install_amnt_incl_vatlcy`,
    `timestamp-0` as `timestamp`,
    `systemId-2000000000` as `system_id`,
    `SystemCreatedAt-2000000001` as `system_created_at`,
    `SystemCreatedBy-2000000002` as `system_created_by`,
    `SystemModifiedAt-2000000003` as `system_modified_at`,
    `SystemModifiedBy-2000000004` as `system_modified_by`,
    `$Company` as `company`,
    _metadata
from
    stream read_files(
        '/Volumes/{{ var("source")["database"] }}/{{ var("source")["schema"] }}/{{ var("source")["volume"] }}/deltas/ProjectInstallment-11012018/*.csv',
        schema
        => '`ProjectNo-10` string, `Principal-20` string, `Scheme-25` string, `InstallmentNo-30` string, `Description-40` string, `CommissionNo-50` string, `CostObject-60` string, `VATProdPostingGroup-70` string, `InstallmentAmountLCY-80` decimal(12,5), `InstallmentAmount-81` decimal(12,5), `CurrencyCode-82` string, `InstallmentAmountInclVAT-83` decimal(12,5), `Chargeable-90` boolean, `InvoicePriceLCY-100` decimal(12,5), `InvoicePrice-101` decimal(12,5), `ExtensionContract-140` string, `PlotNo-150` string, `Option-160` string, `MainGroup-165` string, `Group-170` string, `SubGroup-180` string, `Points-200` int, `Pointstobeinvoiced-210` int, `Element-220` string, `InstallmentMotivationDate-230` date, `InstallmentOverview-235` int, `PercentagePoints-240` decimal(12,5), `TotalPercentagePoints-245` decimal(12,5), `ExpectedInvoiceDate-250` date, `LastInstallment-260` boolean, `DueDateBase-270` date, `DueDateActual-290` date, `InterestInstallment-300` string, `InterestInstNoContract-310` string, `InterestInstNoTransfer-320` string, `InstallmentSchemeSerNo-330` string, `PercentageContractAmount-340` decimal(12,5), `CostComponent-360` string, `PeriodStart-410` date, `PeriodEnd-420` date, `VATAmountLongLease-430` decimal(12,5), `InvoiceVATAmountLongLease-440` decimal(12,5), `SpecificPaymentTermsCode-450` string, `ProjectActivityNo-500` string, `RAWFinalInstallment-510` boolean, `OrigContractInstallmentDate-520` date, `Remarks-530` string, `AdvancePayment-540` boolean, `OptionQuoteNo-610` string, `SettlementSheetNo-620` string, `InvoicePriceInclVATLCY-630` decimal(12,5), `InvoicePriceInclVAT-640` decimal(12,5), `InstallAmntInclVATLCY-650` decimal(12,5), `timestamp-0` bigint, `systemId-2000000000` string, `SystemCreatedAt-2000000001` timestamp, `SystemCreatedBy-2000000002` string, `SystemModifiedAt-2000000003` timestamp, `SystemModifiedBy-2000000004` string, `$Company` string',
        header => 'true',
        sep => ',',
        escape => '\\',
        encoding => 'UTF-8',
        quote => '"'
    )
