select
    `ProjectNo-10` as `project_no`,
    `PrognosisDate-20` as `prognosis_date`,
    `Comment-30` as `comment`,
    `Text-50` as `text`,
    `RoughPrognosisEndResult-60` as `rough_prognosis_end_result`,
    `MainProjectNo-70` as `main_project_no`,
    `DepartmentCode-75` as `department_code`,
    `RoughPrognosisTotalCost-80` as `rough_prognosis_total_cost`,
    `RoughPrognosisTotalRevenues-90` as `rough_prognosis_total_revenues`,
    `ContractAmountProject-100` as `contract_amount_project`,
    `PlotPriceProject-105` as `plot_price_project`,
    `ContractAmountExtensions-110` as `contract_amount_extensions`,
    `ContractAmountOptions-115` as `contract_amount_options`,
    `ContractAmountInvoiced-120` as `contract_amount_invoiced`,
    `PlotPriceInvoiced-125` as `plot_price_invoiced`,
    `ExtensionAmountInvoiced-130` as `extension_amount_invoiced`,
    `OptionAmountInvoiced-135` as `option_amount_invoiced`,
    `CostPlusInvoiced-140` as `cost_plus_invoiced`,
    `ProjectInvoiced-145` as `project_invoiced`,
    `ContractAmounttoInvoice-150` as `contract_amountto_invoice`,
    `PlotPricetoInvoice-155` as `plot_priceto_invoice`,
    `ExtensionAmounttoInvoice-160` as `extension_amountto_invoice`,
    `OptionAmounttoInvoice-165` as `option_amountto_invoice`,
    `CostPlustoInvoice-170` as `cost_plusto_invoice`,
    `QuotationAmountExtensions-180` as `quotation_amount_extensions`,
    `ToInvoiceInclOfferedExt-190` as `to_invoice_incl_offered_ext`,
    `ExpectedFinishingDate-210` as `expected_finishing_date`,
    `PrognosisLevel-240` as `prognosis_level`,
    `OvhSurchargesCalculated-250` as `ovh_surcharges_calculated`,
    `AlteredAfterCalculation-251` as `altered_after_calculation`,
    `BestCaseCostForecast-260` as `best_case_cost_forecast`,
    `WorstCaseCostForecast-270` as `worst_case_cost_forecast`,
    `BestCaseRevenueForecast-280` as `best_case_revenue_forecast`,
    `WorstCaseRevenueForecast-290` as `worst_case_revenue_forecast`,
    `UsedinClosingProject-490` as `usedin_closing_project`,
    `Fixed-510` as `fixed`,
    `FixPrognosisLine-520` as `fix_prognosis_line`,
    `Createdby-525` as `createdby`,
    `Createdon-526` as `createdon`,
    `Modifiedby-530` as `modifiedby`,
    `LastDateModified-540` as `last_date_modified`,
    `SelectForReporting-560` as `select_for_reporting`,
    `CreatedfromForecast-570` as `createdfrom_forecast`,
    `SortOrder-590` as `sort_order`,
    `CopyCommentsPrevPrognosis-680` as `copy_comments_prev_prognosis`,
    `CalculateProductDiscount-685` as `calculate_product_discount`,
    `CalculateSurcharges-690` as `calculate_surcharges`,
    `CalculateRiscCoverage-700` as `calculate_risc_coverage`,
    `IncludePlotPriceinRevenues-710` as `include_plot_pricein_revenues`,
    `BestCasePrognosis-720` as `best_case_prognosis`,
    `WorstCasePrognosis-730` as `worst_case_prognosis`,
    `ReleaseCalculationResult-740` as `release_calculation_result`,
    `UsedforPrognosisReporting-750` as `usedfor_prognosis_reporting`,
    `PrognTotCostReporting-760` as `progn_tot_cost_reporting`,
    `PrognTotRevReporting-770` as `progn_tot_rev_reporting`,
    `PrognEndResultReporting-780` as `progn_end_result_reporting`,
    `ReportResPreclosureProv-790` as `report_res_preclosure_prov`,
    `PurchResOnlyRelOrders-800` as `purch_res_only_rel_orders`,
    `ExcludeProjectLedgerEntries-810` as `exclude_project_ledger_entries`,
    `Progress-820` as `progress`,
    `GeneralCosts-840` as `general_costs`,
    `Labor-850` as `labor`,
    `Material-860` as `material`,
    `Subcontracting-870` as `subcontracting`,
    `Plant-880` as `plant`,
    `Sundry-890` as `sundry`,
    `Revenues-900` as `revenues`,
    `PERSelectForReporting4PS-11012600` as `per_select_for_reporting_4_ps`,
    `timestamp-0` as `timestamp`,
    `systemId-2000000000` as `system_id`,
    `SystemCreatedAt-2000000001` as `system_created_at`,
    `SystemCreatedBy-2000000002` as `system_created_by`,
    `SystemModifiedAt-2000000003` as `system_modified_at`,
    `SystemModifiedBy-2000000004` as `system_modified_by`,
    `$Company` as `company`,
    _metadata
from
    stream read_files(
        '/Volumes/{{ var("source")["database"] }}/{{ var("source")["schema"] }}/{{ var("source")["volume"] }}/deltas/Prognosis-11012034/*.csv',
        schema
        => '`ProjectNo-10` string, `PrognosisDate-20` date, `Comment-30` string, `Text-50` string, `RoughPrognosisEndResult-60` decimal(12,5), `MainProjectNo-70` string, `DepartmentCode-75` string, `RoughPrognosisTotalCost-80` decimal(12,5), `RoughPrognosisTotalRevenues-90` decimal(12,5), `ContractAmountProject-100` decimal(12,5), `PlotPriceProject-105` decimal(12,5), `ContractAmountExtensions-110` decimal(12,5), `ContractAmountOptions-115` decimal(12,5), `ContractAmountInvoiced-120` decimal(12,5), `PlotPriceInvoiced-125` decimal(12,5), `ExtensionAmountInvoiced-130` decimal(12,5), `OptionAmountInvoiced-135` decimal(12,5), `CostPlusInvoiced-140` decimal(12,5), `ProjectInvoiced-145` decimal(12,5), `ContractAmounttoInvoice-150` decimal(12,5), `PlotPricetoInvoice-155` decimal(12,5), `ExtensionAmounttoInvoice-160` decimal(12,5), `OptionAmounttoInvoice-165` decimal(12,5), `CostPlustoInvoice-170` decimal(12,5), `QuotationAmountExtensions-180` decimal(12,5), `ToInvoiceInclOfferedExt-190` decimal(12,5), `ExpectedFinishingDate-210` date, `PrognosisLevel-240` string, `OvhSurchargesCalculated-250` boolean, `AlteredAfterCalculation-251` boolean, `BestCaseCostForecast-260` decimal(12,5), `WorstCaseCostForecast-270` decimal(12,5), `BestCaseRevenueForecast-280` decimal(12,5), `WorstCaseRevenueForecast-290` decimal(12,5), `UsedinClosingProject-490` boolean, `Fixed-510` boolean, `FixPrognosisLine-520` boolean, `Createdby-525` string, `Createdon-526` date, `Modifiedby-530` string, `LastDateModified-540` date, `SelectForReporting-560` boolean, `CreatedfromForecast-570` boolean, `SortOrder-590` string, `CopyCommentsPrevPrognosis-680` boolean, `CalculateProductDiscount-685` boolean, `CalculateSurcharges-690` boolean, `CalculateRiscCoverage-700` boolean, `IncludePlotPriceinRevenues-710` boolean, `BestCasePrognosis-720` decimal(12,5), `WorstCasePrognosis-730` decimal(12,5), `ReleaseCalculationResult-740` boolean, `UsedforPrognosisReporting-750` boolean, `PrognTotCostReporting-760` decimal(12,5), `PrognTotRevReporting-770` decimal(12,5), `PrognEndResultReporting-780` decimal(12,5), `ReportResPreclosureProv-790` boolean, `PurchResOnlyRelOrders-800` boolean, `ExcludeProjectLedgerEntries-810` boolean, `Progress-820` decimal(12,5), `GeneralCosts-840` string, `Labor-850` string, `Material-860` string, `Subcontracting-870` string, `Plant-880` string, `Sundry-890` string, `Revenues-900` string, `PERSelectForReporting4PS-11012600` boolean, `timestamp-0` bigint, `systemId-2000000000` string, `SystemCreatedAt-2000000001` timestamp, `SystemCreatedBy-2000000002` string, `SystemModifiedAt-2000000003` timestamp, `SystemModifiedBy-2000000004` string, `$Company` string',
        header => 'true',
        sep => ',',
        escape => '\\',
        encoding => 'UTF-8',
        quote => '"'
    )
