select
    `ScheduleName-1` as `schedule_name`,
    `LineNo-2` as `line_no`,
    `RowNo-3` as `row_no`,
    `Description-4` as `description`,
    `Totaling-5` as `totaling`,
    `TotalingType-6` as `totaling_type`,
    `NewPage-7` as `new_page`,
    `Indentation-8` as `indentation`,
    `Show-16` as `show`,
    `Dimension1Totaling-19` as `dimension_1_totaling`,
    `Dimension2Totaling-20` as `dimension_2_totaling`,
    `Dimension3Totaling-21` as `dimension_3_totaling`,
    `Dimension4Totaling-22` as `dimension_4_totaling`,
    `Bold-23` as `bold`,
    `Italic-24` as `italic`,
    `Underline-25` as `underline`,
    `ShowOppositeSign-26` as `show_opposite_sign`,
    `RowType-27` as `row_type`,
    `AmountType-28` as `amount_type`,
    `DoubleUnderline-30` as `double_underline`,
    `HideCurrencySymbol-40` as `hide_currency_symbol`,
    `CostCenterTotaling-1102` as `cost_center_totaling`,
    `CostObjectTotaling-1103` as `cost_object_totaling`,
    `AccountType-11012010` as `account_type`,
    `timestamp-0` as `timestamp`,
    `systemId-2000000000` as `system_id`,
    `SystemCreatedAt-2000000001` as `system_created_at`,
    `SystemCreatedBy-2000000002` as `system_created_by`,
    `SystemModifiedAt-2000000003` as `system_modified_at`,
    `SystemModifiedBy-2000000004` as `system_modified_by`,
    `$Company` as `company`,
    _metadata
from
    stream read_files(
        '/Volumes/{{ var("source")["database"] }}/{{ var("source")["schema"] }}/{{ var("source")["volume"] }}/deltas/AccScheduleLine-85/*.csv',
        schema
        => '`ScheduleName-1` string, `LineNo-2` int, `RowNo-3` string, `Description-4` string, `Totaling-5` string, `TotalingType-6` string, `NewPage-7` boolean, `Indentation-8` int, `Show-16` string, `Dimension1Totaling-19` string, `Dimension2Totaling-20` string, `Dimension3Totaling-21` string, `Dimension4Totaling-22` string, `Bold-23` boolean, `Italic-24` boolean, `Underline-25` boolean, `ShowOppositeSign-26` boolean, `RowType-27` string, `AmountType-28` string, `DoubleUnderline-30` boolean, `HideCurrencySymbol-40` boolean, `CostCenterTotaling-1102` string, `CostObjectTotaling-1103` string, `AccountType-11012010` string, `timestamp-0` bigint, `systemId-2000000000` string, `SystemCreatedAt-2000000001` timestamp, `SystemCreatedBy-2000000002` string, `SystemModifiedAt-2000000003` timestamp, `SystemModifiedBy-2000000004` string, `$Company` string',
        header => 'true',
        sep => ',',
        escape => '\\',
        encoding => 'UTF-8',
        quote => '"'
    )
