select
    `EntryNo-1` as `entry_no`,
    `VendorLedgerEntryNo-2` as `vendor_ledger_entry_no`,
    `EntryType-3` as `entry_type`,
    `PostingDate-4` as `posting_date`,
    `DocumentType-5` as `document_type`,
    `DocumentNo-6` as `document_no`,
    `Amount-7` as `amount`,
    `AmountLCY-8` as `amount_lcy`,
    `VendorNo-9` as `vendor_no`,
    `CurrencyCode-10` as `currency_code`,
    `UserID-11` as `user_id`,
    `SourceCode-12` as `source_code`,
    `TransactionNo-13` as `transaction_no`,
    `JournalBatchName-14` as `journal_batch_name`,
    `ReasonCode-15` as `reason_code`,
    `DebitAmount-16` as `debit_amount`,
    `CreditAmount-17` as `credit_amount`,
    `DebitAmountLCY-18` as `debit_amount_lcy`,
    `CreditAmountLCY-19` as `credit_amount_lcy`,
    `InitialEntryDueDate-20` as `initial_entry_due_date`,
    `InitialEntryGlobalDim1-21` as `initial_entry_global_dim_1`,
    `InitialEntryGlobalDim2-22` as `initial_entry_global_dim_2`,
    `GenBusPostingGroup-24` as `gen_bus_posting_group`,
    `GenProdPostingGroup-25` as `gen_prod_posting_group`,
    `UseTax-29` as `use_tax`,
    `VATBusPostingGroup-30` as `vat_bus_posting_group`,
    `VATProdPostingGroup-31` as `vat_prod_posting_group`,
    `InitialDocumentType-35` as `initial_document_type`,
    `AppliedVendLedgerEntryNo-36` as `applied_vend_ledger_entry_no`,
    `Unapplied-37` as `unapplied`,
    `UnappliedbyEntryNo-38` as `unappliedby_entry_no`,
    `RemainingPmtDiscPossible-39` as `remaining_pmt_disc_possible`,
    `MaxPaymentTolerance-40` as `max_payment_tolerance`,
    `TaxJurisdictionCode-41` as `tax_jurisdiction_code`,
    `ApplicationNo-42` as `application_no`,
    `LedgerEntryAmount-43` as `ledger_entry_amount`,
    `PostingGroup-44` as `posting_group`,
    `ExchRateAdjmtRegNo-45` as `exch_rate_adjmt_reg_no`,
    `DocumentDate-11012001` as `document_date`,
    `DueDate-11012010` as `due_date`,
    `InitialEntryJobNo-11012020` as `initial_entry_job_no`,
    `InitialEntrySubcontractNo-11012030` as `initial_entry_subcontract_no`,
    `timestamp-0` as `timestamp`,
    `systemId-2000000000` as `system_id`,
    `SystemCreatedAt-2000000001` as `system_created_at`,
    `SystemCreatedBy-2000000002` as `system_created_by`,
    `SystemModifiedAt-2000000003` as `system_modified_at`,
    `SystemModifiedBy-2000000004` as `system_modified_by`,
    `$Company` as `company`,
    _metadata
from
    stream read_files(
        '/Volumes/{{ var("source")["database"] }}/{{ var("source")["schema"] }}/{{ var("source")["volume"] }}/deltas/DetailedVendorLedgEntry-380/*.csv',
        schema
        => '`EntryNo-1` int, `VendorLedgerEntryNo-2` int, `EntryType-3` string, `PostingDate-4` date, `DocumentType-5` string, `DocumentNo-6` string, `Amount-7` decimal(12,5), `AmountLCY-8` decimal(12,5), `VendorNo-9` string, `CurrencyCode-10` string, `UserID-11` string, `SourceCode-12` string, `TransactionNo-13` int, `JournalBatchName-14` string, `ReasonCode-15` string, `DebitAmount-16` decimal(12,5), `CreditAmount-17` decimal(12,5), `DebitAmountLCY-18` decimal(12,5), `CreditAmountLCY-19` decimal(12,5), `InitialEntryDueDate-20` date, `InitialEntryGlobalDim1-21` string, `InitialEntryGlobalDim2-22` string, `GenBusPostingGroup-24` string, `GenProdPostingGroup-25` string, `UseTax-29` boolean, `VATBusPostingGroup-30` string, `VATProdPostingGroup-31` string, `InitialDocumentType-35` string, `AppliedVendLedgerEntryNo-36` int, `Unapplied-37` boolean, `UnappliedbyEntryNo-38` int, `RemainingPmtDiscPossible-39` decimal(12,5), `MaxPaymentTolerance-40` decimal(12,5), `TaxJurisdictionCode-41` string, `ApplicationNo-42` int, `LedgerEntryAmount-43` boolean, `PostingGroup-44` string, `ExchRateAdjmtRegNo-45` int, `DocumentDate-11012001` date, `DueDate-11012010` date, `InitialEntryJobNo-11012020` string, `InitialEntrySubcontractNo-11012030` string, `timestamp-0` bigint, `systemId-2000000000` string, `SystemCreatedAt-2000000001` timestamp, `SystemCreatedBy-2000000002` string, `SystemModifiedAt-2000000003` timestamp, `SystemModifiedBy-2000000004` string, `$Company` string',
        header => 'true',
        sep => ',',
        escape => '\\',
        encoding => 'UTF-8',
        quote => '"'
    )
