select
    `No-1` as `no`,
    `Name-2` as `name`,
    `SearchName-3` as `search_name`,
    `AccountType-4` as `account_type`,
    `GlobalDimension1Code-6` as `global_dimension_1_code`,
    `GlobalDimension2Code-7` as `global_dimension_2_code`,
    `AccountCategory-8` as `account_category`,
    `IncomeBalance-9` as `income_balance`,
    `DebitCredit-10` as `debit_credit`,
    `No2-11` as `no_2`,
    `Blocked-13` as `blocked`,
    `DirectPosting-14` as `direct_posting`,
    `ReconciliationAccount-16` as `reconciliation_account`,
    `NewPage-17` as `new_page`,
    `NoofBlankLines-18` as `noof_blank_lines`,
    `Indentation-19` as `indentation`,
    `SourceCurrencyCode-20` as `source_currency_code`,
    `SourceCurrencyPosting-21` as `source_currency_posting`,
    `SourceCurrencyRevaluation-22` as `source_currency_revaluation`,
    `UnrealizedRevaluation-23` as `unrealized_revaluation`,
    `LastModifiedDateTime-25` as `last_modified_date_time`,
    `LastDateModified-26` as `last_date_modified`,
    `Totaling-34` as `totaling`,
    `ConsolTranslationMethod-39` as `consol_translation_method`,
    `ConsolDebitAcc-40` as `consol_debit_acc`,
    `ConsolCreditAcc-41` as `consol_credit_acc`,
    `GenPostingType-43` as `gen_posting_type`,
    `GenBusPostingGroup-44` as `gen_bus_posting_group`,
    `GenProdPostingGroup-45` as `gen_prod_posting_group`,
    `AutomaticExtTexts-49` as `automatic_ext_texts`,
    `TaxAreaCode-54` as `tax_area_code`,
    `TaxLiable-55` as `tax_liable`,
    `TaxGroupCode-56` as `tax_group_code`,
    `VATBusPostingGroup-57` as `vat_bus_posting_group`,
    `VATProdPostingGroup-58` as `vat_prod_posting_group`,
    `ExchangeRateAdjustment-63` as `exchange_rate_adjustment`,
    `DefaultICPartnerGLAccNo-66` as `default_ic_partner_gl_acc_no`,
    `AccountSubcategoryEntryNo-80` as `account_subcategory_entry_no`,
    `ExcludeFromConsolidation-83` as `exclude_from_consolidation`,
    `CostTypeNo-1100` as `cost_type_no`,
    `DefaultDeferralTemplateCode-1700` as `default_deferral_template_code`,
    `APIAccountType-9000` as `api_account_type`,
    `OmitDefaultDescrinJnl-11400` as `omit_default_descrin_jnl`,
    `ReviewPolicy-22200` as `review_policy`,
    `WIPAccount-11012000` as `wip_account`,
    `ImportPostingInformation-11012010` as `import_posting_information`,
    `DepartmentTotaling-11012020` as `department_totaling`,
    `CashFlowPaymentTermsCode-11012030` as `cash_flow_payment_terms_code`,
    `CashFlowVAT-11012040` as `cash_flow_vat`,
    `CashFlowTaxPeriod-11012050` as `cash_flow_tax_period`,
    `CashFlowTaxType-11012060` as `cash_flow_tax_type`,
    `timestamp-0` as `timestamp`,
    `systemId-2000000000` as `system_id`,
    `SystemCreatedAt-2000000001` as `system_created_at`,
    `SystemCreatedBy-2000000002` as `system_created_by`,
    `SystemModifiedAt-2000000003` as `system_modified_at`,
    `SystemModifiedBy-2000000004` as `system_modified_by`,
    `$Company` as `company`,
    _metadata
from
    stream read_files(
        '/Volumes/{{ var("source")["database"] }}/{{ var("source")["schema"] }}/{{ var("source")["volume"] }}/deltas/GLAccount-15/*.csv',
        schema
        => '`No-1` string, `Name-2` string, `SearchName-3` string, `AccountType-4` string, `GlobalDimension1Code-6` string, `GlobalDimension2Code-7` string, `AccountCategory-8` string, `IncomeBalance-9` string, `DebitCredit-10` string, `No2-11` string, `Blocked-13` boolean, `DirectPosting-14` boolean, `ReconciliationAccount-16` boolean, `NewPage-17` boolean, `NoofBlankLines-18` int, `Indentation-19` int, `SourceCurrencyCode-20` string, `SourceCurrencyPosting-21` string, `SourceCurrencyRevaluation-22` boolean, `UnrealizedRevaluation-23` boolean, `LastModifiedDateTime-25` timestamp, `LastDateModified-26` date, `Totaling-34` string, `ConsolTranslationMethod-39` string, `ConsolDebitAcc-40` string, `ConsolCreditAcc-41` string, `GenPostingType-43` string, `GenBusPostingGroup-44` string, `GenProdPostingGroup-45` string, `AutomaticExtTexts-49` boolean, `TaxAreaCode-54` string, `TaxLiable-55` boolean, `TaxGroupCode-56` string, `VATBusPostingGroup-57` string, `VATProdPostingGroup-58` string, `ExchangeRateAdjustment-63` string, `DefaultICPartnerGLAccNo-66` string, `AccountSubcategoryEntryNo-80` int, `ExcludeFromConsolidation-83` boolean, `CostTypeNo-1100` string, `DefaultDeferralTemplateCode-1700` string, `APIAccountType-9000` string, `OmitDefaultDescrinJnl-11400` boolean, `ReviewPolicy-22200` string, `WIPAccount-11012000` boolean, `ImportPostingInformation-11012010` boolean, `DepartmentTotaling-11012020` string, `CashFlowPaymentTermsCode-11012030` string, `CashFlowVAT-11012040` decimal(12,5), `CashFlowTaxPeriod-11012050` string, `CashFlowTaxType-11012060` string, `timestamp-0` bigint, `systemId-2000000000` string, `SystemCreatedAt-2000000001` timestamp, `SystemCreatedBy-2000000002` string, `SystemModifiedAt-2000000003` timestamp, `SystemModifiedBy-2000000004` string, `$Company` string',
        header => 'true',
        sep => ',',
        escape => '\\',
        encoding => 'UTF-8',
        quote => '"'
    )
