select
    `TableNo-1` as `table_no`,
    `No-2` as `no`,
    `TableName-3` as `table_name`,
    `FieldName-4` as `field_name`,
    `Type-5` as `type`,
    `Len-6` as `len`,
    `Class-7` as `class`,
    `Enabled-8` as `enabled`,
    `TypeName-9` as `type_name`,
    `ExternalName-10` as `external_name`,
    `FieldCaption-20` as `field_caption`,
    `RelationTableNo-21` as `relation_table_no`,
    `RelationFieldNo-22` as `relation_field_no`,
    `SQLDataType-23` as `sql_data_type`,
    `OptionString-24` as `option_string`,
    `ObsoleteState-25` as `obsolete_state`,
    `ObsoleteReason-26` as `obsolete_reason`,
    `DataClassification-27` as `data_classification`,
    `IsPartOfPrimaryKey-28` as `is_part_of_primary_key`,
    `AppPackageID-60` as `app_package_id`,
    `AppRuntimePackageID-61` as `app_runtime_package_id`,
    `OptimizeForTextSearch-62` as `optimize_for_text_search`,
    `timestamp-0` as `timestamp`,
    `systemId-2000000000` as `system_id`,
    `SystemCreatedAt-2000000001` as `system_created_at`,
    `SystemCreatedBy-2000000002` as `system_created_by`,
    `SystemModifiedAt-2000000003` as `system_modified_at`,
    `SystemModifiedBy-2000000004` as `system_modified_by`,
    _metadata
from
    stream read_files(
        '/Volumes/{{ var("source")["database"] }}/{{ var("source")["schema"] }}/{{ var("source")["volume"] }}/deltas/Field-2000000041/*.csv',
        schema
        => '`TableNo-1` int, `No-2` int, `TableName-3` string, `FieldName-4` string, `Type-5` string, `Len-6` int, `Class-7` string, `Enabled-8` boolean, `TypeName-9` string, `ExternalName-10` string, `FieldCaption-20` string, `RelationTableNo-21` int, `RelationFieldNo-22` int, `SQLDataType-23` string, `OptionString-24` string, `ObsoleteState-25` string, `ObsoleteReason-26` string, `DataClassification-27` string, `IsPartOfPrimaryKey-28` boolean, `AppPackageID-60` string, `AppRuntimePackageID-61` string, `OptimizeForTextSearch-62` boolean, `timestamp-0` bigint, `systemId-2000000000` string, `SystemCreatedAt-2000000001` timestamp, `SystemCreatedBy-2000000002` string, `SystemModifiedAt-2000000003` timestamp, `SystemModifiedBy-2000000004` string',
        header => 'true',
        sep => ',',
        escape => '\\',
        encoding => 'UTF-8',
        quote => '"'
    )
