select
    `Code-1` as `code`,
    `LastDateModified-2` as `last_date_modified`,
    `LastDateAdjusted-3` as `last_date_adjusted`,
    `ISOCode-4` as `iso_code`,
    `ISONumericCode-5` as `iso_numeric_code`,
    `UnrealizedGainsAcc-6` as `unrealized_gains_acc`,
    `RealizedGainsAcc-7` as `realized_gains_acc`,
    `UnrealizedLossesAcc-8` as `unrealized_losses_acc`,
    `RealizedLossesAcc-9` as `realized_losses_acc`,
    `InvoiceRoundingPrecision-10` as `invoice_rounding_precision`,
    `InvoiceRoundingType-12` as `invoice_rounding_type`,
    `AmountRoundingPrecision-13` as `amount_rounding_precision`,
    `UnitAmountRoundingPrecision-14` as `unit_amount_rounding_precision`,
    `Description-15` as `description`,
    `AmountDecimalPlaces-17` as `amount_decimal_places`,
    `UnitAmountDecimalPlaces-18` as `unit_amount_decimal_places`,
    `RealizedGLGainsAccount-40` as `realized_gl_gains_account`,
    `RealizedGLLossesAccount-41` as `realized_gl_losses_account`,
    `ApplnRoundingPrecision-44` as `appln_rounding_precision`,
    `EMUCurrency-45` as `emu_currency`,
    `CurrencyFactor-46` as `currency_factor`,
    `ResidualGainsAccount-47` as `residual_gains_account`,
    `ResidualLossesAccount-48` as `residual_losses_account`,
    `ConvLCYRndgDebitAcc-50` as `conv_lcy_rndg_debit_acc`,
    `ConvLCYRndgCreditAcc-51` as `conv_lcy_rndg_credit_acc`,
    `MaxVATDifferenceAllowed-52` as `max_vat_difference_allowed`,
    `VATRoundingType-53` as `vat_rounding_type`,
    `PaymentTolerance-54` as `payment_tolerance`,
    `MaxPaymentToleranceAmount-55` as `max_payment_tolerance_amount`,
    `Symbol-56` as `symbol`,
    `LastModifiedDateTime-57` as `last_modified_date_time`,
    `CoupledtoCRM-720` as `coupledto_crm`,
    `timestamp-0` as `timestamp`,
    `systemId-2000000000` as `system_id`,
    `SystemCreatedAt-2000000001` as `system_created_at`,
    `SystemCreatedBy-2000000002` as `system_created_by`,
    `SystemModifiedAt-2000000003` as `system_modified_at`,
    `SystemModifiedBy-2000000004` as `system_modified_by`,
    `$Company` as `company`,
    _metadata
from
    stream read_files(
        '/Volumes/{{ var("source")["database"] }}/{{ var("source")["schema"] }}/{{ var("source")["volume"] }}/deltas/Currency-4/*.csv',
        schema
        => '`Code-1` string, `LastDateModified-2` date, `LastDateAdjusted-3` date, `ISOCode-4` string, `ISONumericCode-5` string, `UnrealizedGainsAcc-6` string, `RealizedGainsAcc-7` string, `UnrealizedLossesAcc-8` string, `RealizedLossesAcc-9` string, `InvoiceRoundingPrecision-10` decimal(12,5), `InvoiceRoundingType-12` string, `AmountRoundingPrecision-13` decimal(12,5), `UnitAmountRoundingPrecision-14` decimal(12,5), `Description-15` string, `AmountDecimalPlaces-17` string, `UnitAmountDecimalPlaces-18` string, `RealizedGLGainsAccount-40` string, `RealizedGLLossesAccount-41` string, `ApplnRoundingPrecision-44` decimal(12,5), `EMUCurrency-45` boolean, `CurrencyFactor-46` decimal(12,5), `ResidualGainsAccount-47` string, `ResidualLossesAccount-48` string, `ConvLCYRndgDebitAcc-50` string, `ConvLCYRndgCreditAcc-51` string, `MaxVATDifferenceAllowed-52` decimal(12,5), `VATRoundingType-53` string, `PaymentTolerance-54` decimal(12,5), `MaxPaymentToleranceAmount-55` decimal(12,5), `Symbol-56` string, `LastModifiedDateTime-57` timestamp, `CoupledtoCRM-720` boolean, `timestamp-0` bigint, `systemId-2000000000` string, `SystemCreatedAt-2000000001` timestamp, `SystemCreatedBy-2000000002` string, `SystemModifiedAt-2000000003` timestamp, `SystemModifiedBy-2000000004` string, `$Company` string',
        header => 'true',
        sep => ',',
        escape => '\\',
        encoding => 'UTF-8',
        quote => '"'
    )
